### ISSUE TITLE
Wagumi Cats 絵の表示作成 

### ISSUE THREAD

**Issue by shunkakinoki** [wagumi/wagumi#12]
目的: Randomでwagumi catsのnftの絵を表示させるようにする。

とりあえず、https://art.mosh.lol みたいな感じで、ランダムに絵を取得して表示する感じで良いかなと思っております。

Rootに作るので、component含めて以下に作成できればなと。

https://github.com/wagumi/wagumi/blob/main/packages/cats/src/pages/index.tsx

**Comment by shunkakinoki** [comment]
結構説明省いていますが、なんとなくイメージ伝われば幸いです。

**Comment by sakimyto** [comment]
`components`のディレクトリ構成について

ディレクトリ構成はある程度同じ方向向いて作るのがいいかなーと思ったので、提起として一案投げておきます！
Componentは結構すぐ細分化していくと思うので！(とりあえず書く人が決めればなんでもいいと思います)

```
project_root/
    └── components/
        ├── atoms/
        ├── molecules/
        ├── organisms/
        └── templates/
```

- src/components/

  ```text
  UIコンポーネントを配置する。
  Atomic Designの分類に基づいてコンポーネント振り分ける。
  ```

- src/components/atoms/

  ```text
  部品となる汎用UIコンポーネントを配置する。
  単体で存在できるUIならここに配置する。
  ```

- src/components/molecules/

  ```text
  複数のUIコンポーネントを組み合わせたUIコンポーネントを配置する。
  特定のコンテキストに依存しないようして再利用を考慮する。
  UI制御のロジックが必要であればhooksを提供する。
  ```

- src/components/organisms/

  ```text
  特定のコンテキストに依存したUIコンポーネントを配置する。
  再利用はあまり考えなくてもいい。
  storesやapiに密結合していてもいい。
  ```

- src/components/templates/

  ```text
  ページ全体のスケルトンになるUIコンポーネントを配置する。
  ページのアクセス制御やレイアウト等を含んだコンポーネント。
  ```

引用元
https://qiita.com/kentt/items/c86782b481ec175a57e2

**Comment by shunkakinoki** [comment]
うおおお最高です！！！！

**Comment by shunkakinoki** [comment]
上記で完璧だと思います。

atomic design, 最初プロジェクト始める時、結構悩んだりしますよね〜

**Comment by Naokiakazawa** [comment]
賛成です！
今回は複数人が触ることが想定できるので、最初から綺麗にatomic designで揃えていく形がいいと思います！

（フロントエンドのディレクトリ構成、僕もいまだに悩みまくりますw）

**Comment by sakimyto** [comment]
@shunkakinoki @Naokiakazawa ありがとうございます！

@どなたか
パッとすぐに取りかかる時間が無さそうなので、他の方着手する場合はcomponentsディレクトリ整理から着手していいたたげるとー！
言い出しっぺなのにすいません…！

**Comment by shunkakinoki** [comment]
ローンチに伴いクローズさせていただきます！
