### ISSUE TITLE
contracts のファイルを整理する

### ISSUE THREAD

**Issue by tadashim** [wagumi/wagumi#41]
NFT のデプロイとテストが動くようになったので、今後使わなさそうなコントラクトは整理をしておいた方が良さそう。
コントラクト名とファイル名も実態に合わせたい。

- Greeter コントラクトの削除
- Token コントラクトの削除
- NFT コントラクトの名称およびファイル変更: `NFT` -> `WagumiCats`

**Comment by tadashim** [comment]
Token コントラクトとか残した方が良ければ教えてください。

**Comment by shunkakinoki** [comment]
ローンチに伴いクローズさせていただきます！
