### ISSUE TITLE
Wagumi Cats スマートコントラクト 仕様書

### ISSUE THREAD

**Issue by shunkakinoki** [wagumi/wagumi#8]
目的: Wagumi Catsのスマコン開発

具体的なイメージ:
- Deploy先はethereumのmainnetで、フリーミント(＝ガス以外は無料)
-  1週間Whitelist専用のミント期間あり、その後一般開放 
(Whitelistのアドレスは最初のdiscordメンバー1,000人のアドレスを取得）
- 0~9個目は、Whitelist期間中は、ミント不可 
=> Whitelist終了後もし売り切れていなかったら、Wagumi DAOへミント

コード:https://github.com/wagumi/wagumi/blob/main/packages/contracts/contracts/NFT.sol

背景: https://discord.com/channels/914960638365810748/914988919362293760/917876301577199656

仕様:
- Max supply 1,000
- Whitelist期間はwhitelistのアドレスのみmintできるようにする
- Whitelist期間は0~9個目はMint不可

関連:
- #9
- #19
- #21

**Comment by shunkakinoki** [comment]
Metadata先は: https://cats.wagumi.xyz/metadata/1
画像データ先は: https://cats.wagumi.xyz/1.png

**Comment by shunkakinoki** [comment]
Contractイメージ像（ご意見お聞きしたいです。)

 拡張性の観点から
 erc721 Enumerableを導入？
 https://docs.openzeppelin.com/contracts/2.x/api/token/erc721#ERC721Enumerable

**Comment by shunkakinoki** [comment]
あとそうだ、test走ってます！

https://github.com/wagumi/wagumi/actions/workflows/test.yml

**Comment by tadashim** [comment]
> 拡張性の観点から erc721 Enumerableを導入？ 
gas costが上がるので、必要がなければ入れない派です。

**Comment by shunkakinoki** [comment]
ご意見有難うございます！

確かに、そうですよねw

上記のcontract, gasの最適化全然できていないので、余裕があればしたい（教えていただきたいです。。）！

**Comment by tadashim** [comment]
具体的には下記3つの関数を使うかどうかで決まってくると思います。
```
totalSupply()
tokenOfOwnerByIndex(owner, index)
tokenByIndex(index)
```
enumerableは古い時代の名残りなので処理がイケておらず（arrayが返せない）、tokenIdの一覧を取得するならオフチェーンやTheGraphを使う傾向が最近増えているという認識です！

**Comment by hiroism007** [comment]
ホワイトリストの実現方法はどのような手法を考えていますか？それによりコントラクト（そして mint サイト）の実装が変わってくると思います。具体的には大きく2パターン考えられると思います。

1. mint サイトのサーバーサイト等での署名と、コントラクトでの署名検証パターン
2. ホワイトリスト者のアドレスで作成したマークルツリー検証パターン

前者は、mint サイト等のサーバー側で署名を作成しそれをホワイトリストの方が利用してコントラクトの mint を実行するパターンです。この場合、コントラクトに mint サイトで署名する鍵のアドレスを持っておく必要があります。後者は、事前にホワイトリスト者のアドレスを集めて、そこから生成されてマークルルートをコントラクトにもたせておく必要があります。

**Comment by tadashim** [comment]
自分はコントラクト側だけで制御できる後者の方が良さそうだと思っています。

**Comment by shunkakinoki** [comment]
@hiroism007 @tadashim 
お二人方ともご意見有難うございます！
少々nftについて仕様に変更があり…
そちら含めて明日中にアナウンスできればと思っております！

**Comment by shunkakinoki** [comment]
ローンチに伴いクローズさせていただきます！
